#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00
#PBS -l mem=4gb

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_report

singularity exec docker://brainlife/mne:1.2.1 python3 main.py
